# Generated by Django 3.0.2 on 2020-05-04 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='', max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Classroom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(default='', max_length=9)),
                ('class_name', models.CharField(default='', max_length=50)),
                ('admin_name', models.CharField(default='', max_length=50)),
                ('date1', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('section', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=150)),
            ],
            options={
                'unique_together': {('class_code', 'slug')},
            },
        ),
    ]
