# Generated by Django 3.0.2 on 2020-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0002_join_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_classroom',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=130, null=True),
        ),
    ]
