# Generated by Django 3.0.2 on 2020-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0003_auto_20200504_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_student',
            name='user1',
        ),
        migrations.AddField(
            model_name='join_student',
            name='user',
            field=models.CharField(default='', max_length=130),
        ),
    ]
