# Generated by Django 3.0.2 on 2020-05-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0004_auto_20200504_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join_student',
            old_name='classrooms',
            new_name='class_code',
        ),
    ]
