# Generated by Django 3.0.2 on 2020-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0005_auto_20200504_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_student',
            name='class_code',
        ),
        migrations.AddField(
            model_name='join_student',
            name='join_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
