# Generated by Django 3.0.2 on 2020-05-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0006_auto_20200505_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_student',
            name='join_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom'),
        ),
    ]
