# Generated by Django 3.0.2 on 2020-05-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0007_auto_20200508_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que1', models.CharField(default='', max_length=500)),
                ('ans1', models.IntegerField(blank=True, null=True)),
                ('que2', models.CharField(default='', max_length=500)),
                ('ans2', models.IntegerField(blank=True, null=True)),
                ('que3', models.CharField(default='', max_length=500)),
                ('ans3', models.IntegerField(blank=True, null=True)),
                ('que4', models.CharField(default='', max_length=500)),
                ('ans4', models.IntegerField(blank=True, null=True)),
                ('que5', models.CharField(default='', max_length=500)),
                ('ans5', models.IntegerField(blank=True, null=True)),
                ('scores', models.IntegerField(blank=True, null=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
    ]
