# Generated by Django 3.0.2 on 2020-05-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0008_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_classroom',
            old_name='class_id',
            new_name='sno',
        ),
        migrations.RemoveField(
            model_name='join_student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='join_student',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
