# Generated by Django 3.0.2 on 2020-05-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0009_auto_20200508_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_classroom',
            old_name='sno',
            new_name='class_id',
        ),
    ]
