# Generated by Django 3.0.2 on 2020-05-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0010_auto_20200508_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sno',
            new_name='sno1',
        ),
    ]
