# Generated by Django 3.0.2 on 2020-05-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0011_auto_20200508_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_student',
            name='sno',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
