# Generated by Django 3.0.2 on 2020-05-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0012_auto_20200508_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join_student',
            old_name='sno',
            new_name='sno2',
        ),
    ]
