# Generated by Django 3.0.2 on 2020-05-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0015_auto_20200509_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField(blank=True, null=True)),
                ('test_code1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test2', models.IntegerField(blank=True, null=True)),
                ('test_code2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test3', models.IntegerField(blank=True, null=True)),
                ('test_code3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='class_code',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='testcode1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.test1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='testcode2',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.test2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='testcode3',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.test3'),
            preserve_default=False,
        ),
    ]
