# Generated by Django 3.0.2 on 2020-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0016_auto_20200509_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='test1',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='test2',
            name='test2',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='test3',
            name='test3',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
