# Generated by Django 3.0.2 on 2020-05-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0017_auto_20200509_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('sno1', models.AutoField(primary_key=True, serialize=False)),
                ('que1', models.CharField(default='', max_length=500)),
                ('ans1', models.IntegerField(blank=True, null=True)),
                ('que2', models.CharField(default='', max_length=500)),
                ('ans2', models.IntegerField(blank=True, null=True)),
                ('que3', models.CharField(default='', max_length=500)),
                ('ans3', models.IntegerField(blank=True, null=True)),
                ('que4', models.CharField(default='', max_length=500)),
                ('ans4', models.IntegerField(blank=True, null=True)),
                ('que5', models.CharField(default='', max_length=500)),
                ('ans5', models.IntegerField(blank=True, null=True)),
                ('scores', models.IntegerField(blank=True, null=True)),
                ('testcode1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('sno1', models.AutoField(primary_key=True, serialize=False)),
                ('que1', models.CharField(default='', max_length=500)),
                ('ans1', models.IntegerField(blank=True, null=True)),
                ('que2', models.CharField(default='', max_length=500)),
                ('ans2', models.IntegerField(blank=True, null=True)),
                ('que3', models.CharField(default='', max_length=500)),
                ('ans3', models.IntegerField(blank=True, null=True)),
                ('que4', models.CharField(default='', max_length=500)),
                ('ans4', models.IntegerField(blank=True, null=True)),
                ('que5', models.CharField(default='', max_length=500)),
                ('ans5', models.IntegerField(blank=True, null=True)),
                ('scores', models.IntegerField(blank=True, null=True)),
                ('testcode2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('sno1', models.AutoField(primary_key=True, serialize=False)),
                ('que1', models.CharField(default='', max_length=500)),
                ('ans1', models.IntegerField(blank=True, null=True)),
                ('que2', models.CharField(default='', max_length=500)),
                ('ans2', models.IntegerField(blank=True, null=True)),
                ('que3', models.CharField(default='', max_length=500)),
                ('ans3', models.IntegerField(blank=True, null=True)),
                ('que4', models.CharField(default='', max_length=500)),
                ('ans4', models.IntegerField(blank=True, null=True)),
                ('que5', models.CharField(default='', max_length=500)),
                ('ans5', models.IntegerField(blank=True, null=True)),
                ('scores', models.IntegerField(blank=True, null=True)),
                ('testcode1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examportalquiz1.Create_Classroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='test1',
            name='test_code1',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='test_code2',
        ),
        migrations.RemoveField(
            model_name='test3',
            name='test_code3',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
    ]
