# Generated by Django 3.0.2 on 2020-05-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0018_auto_20200509_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question3',
            old_name='testcode1',
            new_name='testcode3',
        ),
    ]
