# Generated by Django 3.0.2 on 2020-05-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0019_auto_20200509_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question1',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='question2',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='question3',
            name='scores',
        ),
        migrations.AlterField(
            model_name='question1',
            name='ans1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question1',
            name='ans2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question1',
            name='ans3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question1',
            name='ans4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question1',
            name='ans5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ans1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ans2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ans3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ans4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ans5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question3',
            name='ans1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question3',
            name='ans2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question3',
            name='ans3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question3',
            name='ans4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question3',
            name='ans5',
            field=models.CharField(default='', max_length=500),
        ),
    ]
