# Generated by Django 3.0.2 on 2020-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examportalquiz1', '0020_auto_20200509_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_student',
            name='sno2',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
